# Problema2


Lea el archivo 'winemag-data-130k-v2.csv' y realice lo siguiente:

- Explore el dataframe según lo visto en clase
- Realice al menos  4 renombre de columna y 3 creación de nuevas columnas según criterio. Deberá crear las columnas que crea conveniente. 
    Ejemplo: Según el país etiquetelos según continente.

- Genere 4 reportes por agrupamiento de datos. Deberá elegir que reportes realizar
    - Ejemplo: Por contienente mostrar los vinos mejor puntuados
    - Ejemplo2: Promedio de precio de vino y cantidad de reviews obtenidos según pais. Ordenado de mejor a peor 


- Al menos uno de estos datos agrupados deberán ser almacenados en excel o csv
   
   Puede revisar esta solución https://stackoverflow.com/questions/25789264/pandas-dataframegroupby-export-to-excel



### Datos 

winemag-data-130k-v2.csv
- https://github.com/gdelgador/ProgramacionPython202401/blob/main/Modulo5/src/winemag-data-130k-v2.csv

País según continente:
- https://gist.githubusercontent.com/kintero/7d1db891401f56256c79/raw/a61f6d0dda82c3f04d2e6e76c3870552ef6cf0c6/paises.csv

In [12]:
import pandas as pd

df_wine = pd.read_csv("./data/winemag-data-130k-v2.csv")

df_paises = pd.read_csv("./data/paises.csv")

print("Información del dataframe 'winemag-data-130k-v2.csv':")
print(df_wine.info())
df_wine.head()

Información del dataframe 'winemag-data-130k-v2.csv':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65499 entries, 0 to 65498
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             65499 non-null  int64
 1   country                65467 non-null  object
 2   description            65499 non-null  object
 3   designation            46588 non-null  object
 4   points                 65499 non-null  int64
 5   price                  60829 non-null  float64
 6   province               65467 non-null  object
 7   region_1               54744 non-null  object
 8   region_2               25170 non-null  object
 9   taster_name            51856 non-null  object
 10  taster_twitter_handle  49467 non-null  object
 11  title                  65499 non-null  object
 12  variety                65499 non-null  object
 13  winery                 65499 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 7.0+ MB
None

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [14]:
import pandas as pd

df_wine = pd.read_csv("./data/winemag-data-130k-v2.csv")
df_paises = pd.read_csv("./data/paises.csv")

# Renombrar columnas
df_wine = df_wine.rename(columns={'country': 'país', 'description': 'descripción', 'designation': 'denominación', 'points': 'puntuación'})

# Crear nuevas columnas
# 1. Convertir los precios a euros (suponiendo que los precios están en dólares)
df_wine['precio_eur'] = df_wine['price'] * 0.88  # Tasa de cambio: 1 dólar = 0.88 euros
# 2. Calcular el precio por punto
df_wine['precio_por_punto'] = df_wine['precio_eur'] / df_wine['puntuación']

# Fusionar los DataFrames utilizando la columna 'país'
df_wine = df_wine.merge(df_paises[['nombre', 'continente']], left_on='país', right_on='nombre', how='left')
df_wine.drop(columns=['nombre'], inplace=True)

df_wine.head()

,Unnamed: 0,país,descripción,denominación,puntuación,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,precio_eur,precio_por_punto,continente
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,NaN,NaN,NaN
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,13.20,0.151724,Europa
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,12.32,0.141609,NaN
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,11.44,0.131494,NaN
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,57.20,0.657471,NaN

**Reportes:**

In [20]:
# 1. Promedio de puntuación por país:
promedio_puntuacion_pais = df_wine.groupby('país')['puntuación'].mean().sort_values(ascending=False)
print(promedio_puntuacion_pais)

país
England                   91.250000
India                     90.750000
Austria                   89.992661
Germany                   89.808754
Hungary                   89.426230
Canada                    89.212963
France                    88.871487
Morocco                   88.636364
Australia                 88.582838
Italy                     88.566417
US                        88.556095
Luxembourg                88.250000
New Zealand               88.237381
Turkey                    88.232558
Israel                    88.189189
Macedonia                 88.166667
Portugal                  88.134323
South Africa              88.074627
Slovenia                  87.974359
Bulgaria                  87.911765
Serbia                    87.857143
Switzerland               87.750000
Lebanon                   87.650000
Georgia                   87.567568
Spain                     87.259607
Greece                    87.231405
Croatia                   87.204545
Moldova                   87.100000
Slovakia                  87.000000
Armenia                   87.000000
Czech Republic            86.833333
Argentina                 86.681699
Uruguay                   86.655738
Chile                     86.574402
Romania                   86.522388
Cyprus                    86.333333
Mexico                    85.967742
Bosnia and Herzegovina    85.000000
Brazil                    84.354839
Peru                      84.000000
Ukraine                   82.800000
Name: puntuación, dtype: float64

In [21]:
# 2. Cantidad de vinos por país y continente:
cantidad_vinos_por_pais_continente = df_wine.groupby(['país', 'continente']).size().reset_index(name='cantidad_vinos')
print(cantidad_vinos_por_pais_continente)

         país           continente  cantidad_vinos
0   Argentina              América            1907
1     Armenia                 Asia               1
2   Australia  Australia y Oceanía            1177
3     Austria               Europa            1635
4    Bulgaria               Europa              68
5       Chile              América            2258
6     Georgia                 Asia              37
7       India                 Asia               4
8      Israel                 Asia             259
9    Portugal               Europa            2963
10     Serbia               Europa               7
11    Uruguay              América              61

In [22]:
# 3. Precio promedio de vinos por continente:
precio_promedio_por_continente = df_wine.groupby('continente')['precio_eur'].mean().sort_values(ascending=False)
print(precio_promedio_por_continente)

continente
Australia y Oceanía    31.492297
Asia                   25.969103
Europa                 23.962907
América                19.599598
Name: precio_eur, dtype: float64

In [23]:
# 4. Cantidad de vinos por rango de puntuación:
bins = [0, 85, 90, 95, 100]
labels = ['80-85', '86-90', '91-95', '96-100']
df_wine['rango_puntuacion'] = pd.cut(df_wine['puntuación'], bins=bins, labels=labels)
cantidad_vinos_por_rango_puntuacion = df_wine.groupby('rango_puntuacion').size().reset_index(name='cantidad_vinos')
print(cantidad_vinos_por_rango_puntuacion)

  rango_puntuacion  cantidad_vinos
0            80-85           11397
1            86-90           36895
2            91-95           16784
3           96-100             423

/tmp/ipykernel_12963/3441222756.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  cantidad_vinos_por_rango_puntuacion = df_wine.groupby('rango_puntuacion').size().reset_index(name='cantidad_vinos')

**Almacenar en excel:**

In [25]:
precio_promedio_por_continente = df_wine.groupby('continente')['precio_eur'].mean().sort_values(ascending=False)

precio_promedio_por_continente_df = precio_promedio_por_continente.reset_index(name='precio_promedio')
precio_promedio_por_continente_df.to_excel('precio_promedio_por_continente.xlsx', index=False)